services:
  # Postgres DB
  postgres:
    image: postgres:15-alpine
    container_name: smunch_payments_pg
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "5435:5432"
    volumes:
      - pgdata_payments:/var/lib/postgresql/data
    networks:
      - default
    #   - smunch-network

  # DB UI
  adminer: #lightweight DB UI at http://localhost:8095
    image: adminer
    restart: unless-stopped
    ports:
      - "8095:8080"
    networks:
      - default
    #   - smunch-network
  
  # payments microservice
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    env_file:
      - .env
    volumes:
      - ./gmail-token.json:/app/gmail-token.json:ro  # ‚Üê Add this line
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    networks:
      - smunch-network
      - default
    restart: unless-stopped

volumes:
  pgdata_payments:

networks:
  smunch-network:
    external: true

